### ISSUE TITLE
How to get spotify refresh token?

### ISSUE THREAD

**Issue by Phoenix-rat** [barbecue/old-website#3]
Spotify access token refresh token nasıl alınacak bilgi verebilir misiniz?

**Comment by barbecue** [comment]
#### Merhaba,

- İlk öncelikle [Spotify developers dashboard](https://developer.spotify.com/dashboard/applications) üzerinden client_id ve client_secret bilgilerinizi alın.
- Ardından `https://accounts.spotify.com/authorize?response_type=code&client_id=$CLIENT_ID&scope=$SCOPE&redirect_uri=$REDIRECT_URI` urlsinde bulunan `$CLIENT_ID`, `$SCOPE`, `$REDIRECT_URI` kısımlarını gerekli şekillerde doldurmalısınız. 
Bizim durumumuzda bize lazım olacak scope `user-read-recently-played`. 
Bu scope olmadan spotify dinleme geçmişinize erişemezsiniz. Yani bağlantı şu şekilde gözükmelidir. `https://accounts.spotify.com/authorize?response_type=code&client_id=$CLIENT_ID&scope=user-read-recently-played&redirect_uri=https://tuna.one`
- Daha sonra link sizi https://tuna.one?code=$CODE örneğindeki gibi bir kod sayfasına göndericek. Kodunuzu kopyalayın ve kaydedin.
- Daha sonrasında curl aracılığı ile Spotify API'ya request atarak refresh tokeninizi alabilirsiniz.
`curl -d client_id=$CLIENT_ID -d client_secret=$CLIENT_SECRET -d grant_type=authorization_code -d code=$CODE -d redirect_uri=$REDIRECT_URI https://accounts.spotify.com/api/token`

### **For English Tutorial (Source): https://benwiz.com/blog/create-spotify-refresh-token/**
